// ============================================================
// Built-in database of ~100 common foods with nutrition data
// Offline fallback for food search
// ============================================================

export interface CommonFoodItem {
  id: string;
  name: string;
  emoji: string;
  category: "grain" | "protein" | "dairy" | "fruit" | "vegetable" | "snack" | "drink" | "mixed";
  defaultServing: string;
  defaultServingGrams: number;
  carbsGrams: number;
  proteinGrams: number;
  fatGrams: number;
  fiberGrams: number;
  calories: number;
  glycemicEstimate: "low" | "medium" | "high";
}

export const COMMON_FOODS: CommonFoodItem[] = [
  // ---- GRAINS (13 items) ----
  {
    id: "grain-white-rice",
    name: "White Rice",
    emoji: "\uD83C\uDF5A",
    category: "grain",
    defaultServing: "1 cup cooked",
    defaultServingGrams: 186,
    carbsGrams: 45,
    proteinGrams: 4,
    fatGrams: 0.4,
    fiberGrams: 0.6,
    calories: 206,
    glycemicEstimate: "high",
  },
  {
    id: "grain-brown-rice",
    name: "Brown Rice",
    emoji: "\uD83C\uDF5A",
    category: "grain",
    defaultServing: "1 cup cooked",
    defaultServingGrams: 195,
    carbsGrams: 45,
    proteinGrams: 5,
    fatGrams: 1.8,
    fiberGrams: 3.5,
    calories: 216,
    glycemicEstimate: "medium",
  },
  {
    id: "grain-pasta",
    name: "Pasta (Spaghetti)",
    emoji: "\uD83C\uDF5D",
    category: "grain",
    defaultServing: "1 cup cooked",
    defaultServingGrams: 140,
    carbsGrams: 43,
    proteinGrams: 8,
    fatGrams: 1.3,
    fiberGrams: 2.5,
    calories: 220,
    glycemicEstimate: "medium",
  },
  {
    id: "grain-whole-wheat-bread",
    name: "Whole Wheat Bread",
    emoji: "\uD83C\uDF5E",
    category: "grain",
    defaultServing: "1 slice",
    defaultServingGrams: 36,
    carbsGrams: 17,
    proteinGrams: 4,
    fatGrams: 1.5,
    fiberGrams: 2,
    calories: 91,
    glycemicEstimate: "medium",
  },
  {
    id: "grain-white-bread",
    name: "White Bread",
    emoji: "\uD83C\uDF5E",
    category: "grain",
    defaultServing: "1 slice",
    defaultServingGrams: 30,
    carbsGrams: 15,
    proteinGrams: 3,
    fatGrams: 1,
    fiberGrams: 0.6,
    calories: 79,
    glycemicEstimate: "high",
  },
  {
    id: "grain-oatmeal",
    name: "Oatmeal",
    emoji: "\uD83E\uDD63",
    category: "grain",
    defaultServing: "1 cup cooked",
    defaultServingGrams: 234,
    carbsGrams: 27,
    proteinGrams: 5,
    fatGrams: 3.6,
    fiberGrams: 4,
    calories: 154,
    glycemicEstimate: "medium",
  },
  {
    id: "grain-tortilla-flour",
    name: "Flour Tortilla",
    emoji: "\uD83C\uDF2F",
    category: "grain",
    defaultServing: "1 large (10\")",
    defaultServingGrams: 64,
    carbsGrams: 36,
    proteinGrams: 6,
    fatGrams: 5,
    fiberGrams: 2,
    calories: 218,
    glycemicEstimate: "high",
  },
  {
    id: "grain-bagel",
    name: "Bagel",
    emoji: "\uD83E\uDD6F",
    category: "grain",
    defaultServing: "1 medium",
    defaultServingGrams: 105,
    carbsGrams: 55,
    proteinGrams: 10,
    fatGrams: 1.5,
    fiberGrams: 2.3,
    calories: 275,
    glycemicEstimate: "high",
  },
  {
    id: "grain-quinoa",
    name: "Quinoa",
    emoji: "\uD83C\uDF3E",
    category: "grain",
    defaultServing: "1 cup cooked",
    defaultServingGrams: 185,
    carbsGrams: 39,
    proteinGrams: 8,
    fatGrams: 3.5,
    fiberGrams: 5,
    calories: 222,
    glycemicEstimate: "low",
  },
  {
    id: "grain-cereal",
    name: "Breakfast Cereal",
    emoji: "\uD83E\uDD63",
    category: "grain",
    defaultServing: "1 cup",
    defaultServingGrams: 30,
    carbsGrams: 25,
    proteinGrams: 3,
    fatGrams: 1,
    fiberGrams: 1,
    calories: 120,
    glycemicEstimate: "high",
  },
  {
    id: "grain-corn-tortilla",
    name: "Corn Tortilla",
    emoji: "\uD83C\uDF2F",
    category: "grain",
    defaultServing: "1 small (6\")",
    defaultServingGrams: 26,
    carbsGrams: 12,
    proteinGrams: 2,
    fatGrams: 0.7,
    fiberGrams: 1.5,
    calories: 58,
    glycemicEstimate: "medium",
  },
  {
    id: "grain-crackers",
    name: "Saltine Crackers",
    emoji: "\uD83E\uDDC8",
    category: "grain",
    defaultServing: "5 crackers",
    defaultServingGrams: 15,
    carbsGrams: 11,
    proteinGrams: 1,
    fatGrams: 1.7,
    fiberGrams: 0.3,
    calories: 63,
    glycemicEstimate: "high",
  },
  {
    id: "grain-pancakes",
    name: "Pancakes",
    emoji: "\uD83E\uDD5E",
    category: "grain",
    defaultServing: "2 medium",
    defaultServingGrams: 152,
    carbsGrams: 44,
    proteinGrams: 6,
    fatGrams: 7,
    fiberGrams: 1,
    calories: 267,
    glycemicEstimate: "high",
  },

  // ---- PROTEIN (13 items) ----
  {
    id: "protein-chicken-breast",
    name: "Chicken Breast (grilled)",
    emoji: "\uD83C\uDF57",
    category: "protein",
    defaultServing: "6 oz",
    defaultServingGrams: 170,
    carbsGrams: 0,
    proteinGrams: 52,
    fatGrams: 7,
    fiberGrams: 0,
    calories: 281,
    glycemicEstimate: "low",
  },
  {
    id: "protein-ground-beef",
    name: "Ground Beef (80/20)",
    emoji: "\uD83E\uDD69",
    category: "protein",
    defaultServing: "4 oz cooked",
    defaultServingGrams: 113,
    carbsGrams: 0,
    proteinGrams: 22,
    fatGrams: 17,
    fiberGrams: 0,
    calories: 247,
    glycemicEstimate: "low",
  },
  {
    id: "protein-salmon",
    name: "Salmon (baked)",
    emoji: "\uD83E\uDD7E",
    category: "protein",
    defaultServing: "6 oz",
    defaultServingGrams: 170,
    carbsGrams: 0,
    proteinGrams: 40,
    fatGrams: 18,
    fiberGrams: 0,
    calories: 330,
    glycemicEstimate: "low",
  },
  {
    id: "protein-eggs",
    name: "Eggs (large)",
    emoji: "\uD83E\uDD5A",
    category: "protein",
    defaultServing: "2 eggs",
    defaultServingGrams: 100,
    carbsGrams: 1,
    proteinGrams: 13,
    fatGrams: 10,
    fiberGrams: 0,
    calories: 143,
    glycemicEstimate: "low",
  },
  {
    id: "protein-tofu",
    name: "Tofu (firm)",
    emoji: "\uD83E\uDDC8",
    category: "protein",
    defaultServing: "1/2 cup",
    defaultServingGrams: 126,
    carbsGrams: 2,
    proteinGrams: 20,
    fatGrams: 11,
    fiberGrams: 1,
    calories: 183,
    glycemicEstimate: "low",
  },
  {
    id: "protein-turkey-breast",
    name: "Turkey Breast (sliced)",
    emoji: "\uD83E\uDD83",
    category: "protein",
    defaultServing: "4 oz",
    defaultServingGrams: 113,
    carbsGrams: 0,
    proteinGrams: 26,
    fatGrams: 1,
    fiberGrams: 0,
    calories: 120,
    glycemicEstimate: "low",
  },
  {
    id: "protein-shrimp",
    name: "Shrimp (cooked)",
    emoji: "\uD83E\uDD90",
    category: "protein",
    defaultServing: "6 oz",
    defaultServingGrams: 170,
    carbsGrams: 1,
    proteinGrams: 36,
    fatGrams: 2,
    fiberGrams: 0,
    calories: 170,
    glycemicEstimate: "low",
  },
  {
    id: "protein-pork-chop",
    name: "Pork Chop (grilled)",
    emoji: "\uD83E\uDD69",
    category: "protein",
    defaultServing: "6 oz",
    defaultServingGrams: 170,
    carbsGrams: 0,
    proteinGrams: 42,
    fatGrams: 12,
    fiberGrams: 0,
    calories: 282,
    glycemicEstimate: "low",
  },
  {
    id: "protein-black-beans",
    name: "Black Beans",
    emoji: "\uD83E\uDED8",
    category: "protein",
    defaultServing: "1/2 cup cooked",
    defaultServingGrams: 86,
    carbsGrams: 20,
    proteinGrams: 8,
    fatGrams: 0.5,
    fiberGrams: 7.5,
    calories: 114,
    glycemicEstimate: "low",
  },
  {
    id: "protein-peanut-butter",
    name: "Peanut Butter",
    emoji: "\uD83E\uDD5C",
    category: "protein",
    defaultServing: "2 tbsp",
    defaultServingGrams: 32,
    carbsGrams: 7,
    proteinGrams: 8,
    fatGrams: 16,
    fiberGrams: 2,
    calories: 190,
    glycemicEstimate: "low",
  },
  {
    id: "protein-tuna",
    name: "Tuna (canned in water)",
    emoji: "\uD83D\uDC1F",
    category: "protein",
    defaultServing: "1 can (5 oz)",
    defaultServingGrams: 142,
    carbsGrams: 0,
    proteinGrams: 30,
    fatGrams: 1,
    fiberGrams: 0,
    calories: 130,
    glycemicEstimate: "low",
  },
  {
    id: "protein-steak",
    name: "Steak (ribeye)",
    emoji: "\uD83E\uDD69",
    category: "protein",
    defaultServing: "8 oz",
    defaultServingGrams: 227,
    carbsGrams: 0,
    proteinGrams: 46,
    fatGrams: 32,
    fiberGrams: 0,
    calories: 480,
    glycemicEstimate: "low",
  },
  {
    id: "protein-chicken-thigh",
    name: "Chicken Thigh",
    emoji: "\uD83C\uDF57",
    category: "protein",
    defaultServing: "1 thigh",
    defaultServingGrams: 116,
    carbsGrams: 0,
    proteinGrams: 26,
    fatGrams: 10,
    fiberGrams: 0,
    calories: 200,
    glycemicEstimate: "low",
  },

  // ---- DAIRY (10 items) ----
  {
    id: "dairy-whole-milk",
    name: "Whole Milk",
    emoji: "\uD83E\uDD5B",
    category: "dairy",
    defaultServing: "1 cup",
    defaultServingGrams: 244,
    carbsGrams: 12,
    proteinGrams: 8,
    fatGrams: 8,
    fiberGrams: 0,
    calories: 149,
    glycemicEstimate: "low",
  },
  {
    id: "dairy-cheddar",
    name: "Cheddar Cheese",
    emoji: "\uD83E\uDDC0",
    category: "dairy",
    defaultServing: "1 oz",
    defaultServingGrams: 28,
    carbsGrams: 0.4,
    proteinGrams: 7,
    fatGrams: 9,
    fiberGrams: 0,
    calories: 113,
    glycemicEstimate: "low",
  },
  {
    id: "dairy-greek-yogurt",
    name: "Greek Yogurt (plain)",
    emoji: "\uD83E\uDD64",
    category: "dairy",
    defaultServing: "1 cup",
    defaultServingGrams: 227,
    carbsGrams: 9,
    proteinGrams: 20,
    fatGrams: 5,
    fiberGrams: 0,
    calories: 146,
    glycemicEstimate: "low",
  },
  {
    id: "dairy-yogurt-flavored",
    name: "Yogurt (flavored)",
    emoji: "\uD83E\uDD64",
    category: "dairy",
    defaultServing: "1 cup",
    defaultServingGrams: 227,
    carbsGrams: 33,
    proteinGrams: 8,
    fatGrams: 3,
    fiberGrams: 0,
    calories: 190,
    glycemicEstimate: "medium",
  },
  {
    id: "dairy-mozzarella",
    name: "Mozzarella Cheese",
    emoji: "\uD83E\uDDC0",
    category: "dairy",
    defaultServing: "1 oz",
    defaultServingGrams: 28,
    carbsGrams: 0.7,
    proteinGrams: 6,
    fatGrams: 6,
    fiberGrams: 0,
    calories: 85,
    glycemicEstimate: "low",
  },
  {
    id: "dairy-cottage-cheese",
    name: "Cottage Cheese",
    emoji: "\uD83E\uDDC0",
    category: "dairy",
    defaultServing: "1/2 cup",
    defaultServingGrams: 113,
    carbsGrams: 5,
    proteinGrams: 14,
    fatGrams: 5,
    fiberGrams: 0,
    calories: 110,
    glycemicEstimate: "low",
  },
  {
    id: "dairy-cream-cheese",
    name: "Cream Cheese",
    emoji: "\uD83E\uDDC0",
    category: "dairy",
    defaultServing: "2 tbsp",
    defaultServingGrams: 29,
    carbsGrams: 1,
    proteinGrams: 2,
    fatGrams: 10,
    fiberGrams: 0,
    calories: 99,
    glycemicEstimate: "low",
  },
  {
    id: "dairy-ice-cream",
    name: "Ice Cream (vanilla)",
    emoji: "\uD83C\uDF68",
    category: "dairy",
    defaultServing: "1/2 cup",
    defaultServingGrams: 66,
    carbsGrams: 17,
    proteinGrams: 2,
    fatGrams: 7,
    fiberGrams: 0,
    calories: 137,
    glycemicEstimate: "high",
  },
  {
    id: "dairy-butter",
    name: "Butter",
    emoji: "\uD83E\uDDC8",
    category: "dairy",
    defaultServing: "1 tbsp",
    defaultServingGrams: 14,
    carbsGrams: 0,
    proteinGrams: 0.1,
    fatGrams: 12,
    fiberGrams: 0,
    calories: 102,
    glycemicEstimate: "low",
  },
  {
    id: "dairy-skim-milk",
    name: "Skim Milk",
    emoji: "\uD83E\uDD5B",
    category: "dairy",
    defaultServing: "1 cup",
    defaultServingGrams: 244,
    carbsGrams: 12,
    proteinGrams: 8,
    fatGrams: 0.2,
    fiberGrams: 0,
    calories: 83,
    glycemicEstimate: "medium",
  },

  // ---- FRUIT (12 items) ----
  {
    id: "fruit-banana",
    name: "Banana",
    emoji: "\uD83C\uDF4C",
    category: "fruit",
    defaultServing: "1 medium",
    defaultServingGrams: 118,
    carbsGrams: 27,
    proteinGrams: 1.3,
    fatGrams: 0.4,
    fiberGrams: 3.1,
    calories: 105,
    glycemicEstimate: "medium",
  },
  {
    id: "fruit-apple",
    name: "Apple",
    emoji: "\uD83C\uDF4E",
    category: "fruit",
    defaultServing: "1 medium",
    defaultServingGrams: 182,
    carbsGrams: 25,
    proteinGrams: 0.5,
    fatGrams: 0.3,
    fiberGrams: 4.4,
    calories: 95,
    glycemicEstimate: "low",
  },
  {
    id: "fruit-orange",
    name: "Orange",
    emoji: "\uD83C\uDF4A",
    category: "fruit",
    defaultServing: "1 medium",
    defaultServingGrams: 131,
    carbsGrams: 15,
    proteinGrams: 1,
    fatGrams: 0.2,
    fiberGrams: 3,
    calories: 62,
    glycemicEstimate: "low",
  },
  {
    id: "fruit-grapes",
    name: "Grapes",
    emoji: "\uD83C\uDF47",
    category: "fruit",
    defaultServing: "1 cup",
    defaultServingGrams: 151,
    carbsGrams: 27,
    proteinGrams: 1,
    fatGrams: 0.2,
    fiberGrams: 1.4,
    calories: 104,
    glycemicEstimate: "medium",
  },
  {
    id: "fruit-strawberries",
    name: "Strawberries",
    emoji: "\uD83C\uDF53",
    category: "fruit",
    defaultServing: "1 cup",
    defaultServingGrams: 152,
    carbsGrams: 12,
    proteinGrams: 1,
    fatGrams: 0.5,
    fiberGrams: 3,
    calories: 49,
    glycemicEstimate: "low",
  },
  {
    id: "fruit-blueberries",
    name: "Blueberries",
    emoji: "\uD83E\uDED0",
    category: "fruit",
    defaultServing: "1 cup",
    defaultServingGrams: 148,
    carbsGrams: 21,
    proteinGrams: 1,
    fatGrams: 0.5,
    fiberGrams: 3.6,
    calories: 84,
    glycemicEstimate: "medium",
  },
  {
    id: "fruit-watermelon",
    name: "Watermelon",
    emoji: "\uD83C\uDF49",
    category: "fruit",
    defaultServing: "1 cup diced",
    defaultServingGrams: 152,
    carbsGrams: 12,
    proteinGrams: 0.9,
    fatGrams: 0.2,
    fiberGrams: 0.6,
    calories: 46,
    glycemicEstimate: "high",
  },
  {
    id: "fruit-mango",
    name: "Mango",
    emoji: "\uD83E\uDD6D",
    category: "fruit",
    defaultServing: "1 cup sliced",
    defaultServingGrams: 165,
    carbsGrams: 25,
    proteinGrams: 1.4,
    fatGrams: 0.6,
    fiberGrams: 2.6,
    calories: 99,
    glycemicEstimate: "medium",
  },
  {
    id: "fruit-pineapple",
    name: "Pineapple",
    emoji: "\uD83C\uDF4D",
    category: "fruit",
    defaultServing: "1 cup chunks",
    defaultServingGrams: 165,
    carbsGrams: 22,
    proteinGrams: 0.9,
    fatGrams: 0.2,
    fiberGrams: 2.3,
    calories: 82,
    glycemicEstimate: "medium",
  },
  {
    id: "fruit-avocado",
    name: "Avocado",
    emoji: "\uD83E\uDD51",
    category: "fruit",
    defaultServing: "1/2 avocado",
    defaultServingGrams: 68,
    carbsGrams: 6,
    proteinGrams: 1.3,
    fatGrams: 10,
    fiberGrams: 5,
    calories: 114,
    glycemicEstimate: "low",
  },
  {
    id: "fruit-peach",
    name: "Peach",
    emoji: "\uD83C\uDF51",
    category: "fruit",
    defaultServing: "1 medium",
    defaultServingGrams: 150,
    carbsGrams: 14,
    proteinGrams: 1.4,
    fatGrams: 0.4,
    fiberGrams: 2.3,
    calories: 59,
    glycemicEstimate: "low",
  },
  {
    id: "fruit-cherries",
    name: "Cherries",
    emoji: "\uD83C\uDF52",
    category: "fruit",
    defaultServing: "1 cup",
    defaultServingGrams: 138,
    carbsGrams: 22,
    proteinGrams: 1.5,
    fatGrams: 0.3,
    fiberGrams: 2.9,
    calories: 87,
    glycemicEstimate: "low",
  },

  // ---- VEGETABLE (12 items) ----
  {
    id: "veg-broccoli",
    name: "Broccoli",
    emoji: "\uD83E\uDD66",
    category: "vegetable",
    defaultServing: "1 cup chopped",
    defaultServingGrams: 91,
    carbsGrams: 6,
    proteinGrams: 2.6,
    fatGrams: 0.3,
    fiberGrams: 2.4,
    calories: 31,
    glycemicEstimate: "low",
  },
  {
    id: "veg-sweet-potato",
    name: "Sweet Potato",
    emoji: "\uD83C\uDF60",
    category: "vegetable",
    defaultServing: "1 medium",
    defaultServingGrams: 130,
    carbsGrams: 27,
    proteinGrams: 2,
    fatGrams: 0.1,
    fiberGrams: 4,
    calories: 112,
    glycemicEstimate: "medium",
  },
  {
    id: "veg-white-potato",
    name: "White Potato",
    emoji: "\uD83E\uDD54",
    category: "vegetable",
    defaultServing: "1 medium",
    defaultServingGrams: 150,
    carbsGrams: 37,
    proteinGrams: 4.3,
    fatGrams: 0.2,
    fiberGrams: 3.8,
    calories: 163,
    glycemicEstimate: "high",
  },
  {
    id: "veg-spinach",
    name: "Spinach (raw)",
    emoji: "\uD83E\uDD6C",
    category: "vegetable",
    defaultServing: "2 cups",
    defaultServingGrams: 60,
    carbsGrams: 2.2,
    proteinGrams: 1.7,
    fatGrams: 0.2,
    fiberGrams: 1.3,
    calories: 14,
    glycemicEstimate: "low",
  },
  {
    id: "veg-carrots",
    name: "Carrots",
    emoji: "\uD83E\uDD55",
    category: "vegetable",
    defaultServing: "1 medium",
    defaultServingGrams: 61,
    carbsGrams: 6,
    proteinGrams: 0.6,
    fatGrams: 0.1,
    fiberGrams: 1.7,
    calories: 25,
    glycemicEstimate: "low",
  },
  {
    id: "veg-corn",
    name: "Corn (sweet)",
    emoji: "\uD83C\uDF3D",
    category: "vegetable",
    defaultServing: "1 ear",
    defaultServingGrams: 90,
    carbsGrams: 19,
    proteinGrams: 3,
    fatGrams: 1.5,
    fiberGrams: 2,
    calories: 88,
    glycemicEstimate: "medium",
  },
  {
    id: "veg-tomato",
    name: "Tomato",
    emoji: "\uD83C\uDF45",
    category: "vegetable",
    defaultServing: "1 medium",
    defaultServingGrams: 123,
    carbsGrams: 5,
    proteinGrams: 1,
    fatGrams: 0.2,
    fiberGrams: 1.5,
    calories: 22,
    glycemicEstimate: "low",
  },
  {
    id: "veg-bell-pepper",
    name: "Bell Pepper",
    emoji: "\uD83C\uDF36\uFE0F",
    category: "vegetable",
    defaultServing: "1 medium",
    defaultServingGrams: 119,
    carbsGrams: 6,
    proteinGrams: 1,
    fatGrams: 0.3,
    fiberGrams: 2.1,
    calories: 31,
    glycemicEstimate: "low",
  },
  {
    id: "veg-green-beans",
    name: "Green Beans",
    emoji: "\uD83E\uDED8",
    category: "vegetable",
    defaultServing: "1 cup",
    defaultServingGrams: 125,
    carbsGrams: 7,
    proteinGrams: 2,
    fatGrams: 0.1,
    fiberGrams: 3.4,
    calories: 34,
    glycemicEstimate: "low",
  },
  {
    id: "veg-salad-mixed",
    name: "Mixed Salad (no dressing)",
    emoji: "\uD83E\uDD57",
    category: "vegetable",
    defaultServing: "2 cups",
    defaultServingGrams: 85,
    carbsGrams: 4,
    proteinGrams: 1.5,
    fatGrams: 0.2,
    fiberGrams: 2,
    calories: 18,
    glycemicEstimate: "low",
  },
  {
    id: "veg-cucumber",
    name: "Cucumber",
    emoji: "\uD83E\uDD52",
    category: "vegetable",
    defaultServing: "1/2 medium",
    defaultServingGrams: 150,
    carbsGrams: 5,
    proteinGrams: 1,
    fatGrams: 0.2,
    fiberGrams: 0.7,
    calories: 23,
    glycemicEstimate: "low",
  },
  {
    id: "veg-onion",
    name: "Onion",
    emoji: "\uD83E\uDDC5",
    category: "vegetable",
    defaultServing: "1 medium",
    defaultServingGrams: 110,
    carbsGrams: 10,
    proteinGrams: 1.2,
    fatGrams: 0.1,
    fiberGrams: 1.9,
    calories: 44,
    glycemicEstimate: "low",
  },

  // ---- SNACK (12 items) ----
  {
    id: "snack-chips",
    name: "Potato Chips",
    emoji: "\uD83C\uDF5F",
    category: "snack",
    defaultServing: "1 oz (15 chips)",
    defaultServingGrams: 28,
    carbsGrams: 15,
    proteinGrams: 2,
    fatGrams: 10,
    fiberGrams: 1,
    calories: 152,
    glycemicEstimate: "high",
  },
  {
    id: "snack-granola-bar",
    name: "Granola Bar",
    emoji: "\uD83C\uDF6B",
    category: "snack",
    defaultServing: "1 bar",
    defaultServingGrams: 42,
    carbsGrams: 29,
    proteinGrams: 3,
    fatGrams: 7,
    fiberGrams: 2,
    calories: 190,
    glycemicEstimate: "high",
  },
  {
    id: "snack-almonds",
    name: "Almonds",
    emoji: "\uD83E\uDD5C",
    category: "snack",
    defaultServing: "1/4 cup",
    defaultServingGrams: 36,
    carbsGrams: 8,
    proteinGrams: 8,
    fatGrams: 18,
    fiberGrams: 4,
    calories: 207,
    glycemicEstimate: "low",
  },
  {
    id: "snack-trail-mix",
    name: "Trail Mix",
    emoji: "\uD83E\uDD5C",
    category: "snack",
    defaultServing: "1/4 cup",
    defaultServingGrams: 40,
    carbsGrams: 17,
    proteinGrams: 5,
    fatGrams: 13,
    fiberGrams: 2,
    calories: 200,
    glycemicEstimate: "medium",
  },
  {
    id: "snack-pretzels",
    name: "Pretzels",
    emoji: "\uD83E\uDD68",
    category: "snack",
    defaultServing: "1 oz",
    defaultServingGrams: 28,
    carbsGrams: 23,
    proteinGrams: 3,
    fatGrams: 1,
    fiberGrams: 1,
    calories: 108,
    glycemicEstimate: "high",
  },
  {
    id: "snack-chocolate",
    name: "Milk Chocolate",
    emoji: "\uD83C\uDF6B",
    category: "snack",
    defaultServing: "1 bar (1.5 oz)",
    defaultServingGrams: 43,
    carbsGrams: 26,
    proteinGrams: 3,
    fatGrams: 13,
    fiberGrams: 1,
    calories: 235,
    glycemicEstimate: "high",
  },
  {
    id: "snack-dark-chocolate",
    name: "Dark Chocolate (70%+)",
    emoji: "\uD83C\uDF6B",
    category: "snack",
    defaultServing: "1 oz",
    defaultServingGrams: 28,
    carbsGrams: 13,
    proteinGrams: 2,
    fatGrams: 12,
    fiberGrams: 3,
    calories: 170,
    glycemicEstimate: "low",
  },
  {
    id: "snack-popcorn",
    name: "Popcorn (air-popped)",
    emoji: "\uD83C\uDF7F",
    category: "snack",
    defaultServing: "3 cups popped",
    defaultServingGrams: 24,
    carbsGrams: 19,
    proteinGrams: 3,
    fatGrams: 1,
    fiberGrams: 3.5,
    calories: 93,
    glycemicEstimate: "medium",
  },
  {
    id: "snack-cookie",
    name: "Chocolate Chip Cookie",
    emoji: "\uD83C\uDF6A",
    category: "snack",
    defaultServing: "1 large",
    defaultServingGrams: 40,
    carbsGrams: 24,
    proteinGrams: 2,
    fatGrams: 9,
    fiberGrams: 0.5,
    calories: 180,
    glycemicEstimate: "high",
  },
  {
    id: "snack-fruit-snacks",
    name: "Fruit Snacks",
    emoji: "\uD83C\uDF53",
    category: "snack",
    defaultServing: "1 pouch",
    defaultServingGrams: 25,
    carbsGrams: 21,
    proteinGrams: 0,
    fatGrams: 0,
    fiberGrams: 0,
    calories: 80,
    glycemicEstimate: "high",
  },
  {
    id: "snack-cheese-stick",
    name: "String Cheese",
    emoji: "\uD83E\uDDC0",
    category: "snack",
    defaultServing: "1 stick",
    defaultServingGrams: 28,
    carbsGrams: 0.5,
    proteinGrams: 7,
    fatGrams: 5,
    fiberGrams: 0,
    calories: 80,
    glycemicEstimate: "low",
  },
  {
    id: "snack-hummus",
    name: "Hummus",
    emoji: "\uD83E\uDED8",
    category: "snack",
    defaultServing: "1/4 cup",
    defaultServingGrams: 62,
    carbsGrams: 9,
    proteinGrams: 4,
    fatGrams: 6,
    fiberGrams: 2,
    calories: 104,
    glycemicEstimate: "low",
  },

  // ---- DRINK (10 items) ----
  {
    id: "drink-orange-juice",
    name: "Orange Juice",
    emoji: "\uD83E\uDDC3",
    category: "drink",
    defaultServing: "1 cup",
    defaultServingGrams: 248,
    carbsGrams: 26,
    proteinGrams: 2,
    fatGrams: 0.5,
    fiberGrams: 0.5,
    calories: 112,
    glycemicEstimate: "high",
  },
  {
    id: "drink-soda",
    name: "Soda (regular)",
    emoji: "\uD83E\uDD64",
    category: "drink",
    defaultServing: "12 oz can",
    defaultServingGrams: 355,
    carbsGrams: 39,
    proteinGrams: 0,
    fatGrams: 0,
    fiberGrams: 0,
    calories: 140,
    glycemicEstimate: "high",
  },
  {
    id: "drink-coffee-black",
    name: "Coffee (black)",
    emoji: "\u2615",
    category: "drink",
    defaultServing: "1 cup",
    defaultServingGrams: 237,
    carbsGrams: 0,
    proteinGrams: 0.3,
    fatGrams: 0,
    fiberGrams: 0,
    calories: 2,
    glycemicEstimate: "low",
  },
  {
    id: "drink-latte",
    name: "Latte (whole milk)",
    emoji: "\u2615",
    category: "drink",
    defaultServing: "12 oz",
    defaultServingGrams: 355,
    carbsGrams: 13,
    proteinGrams: 8,
    fatGrams: 7,
    fiberGrams: 0,
    calories: 150,
    glycemicEstimate: "low",
  },
  {
    id: "drink-smoothie",
    name: "Fruit Smoothie",
    emoji: "\uD83E\uDD64",
    category: "drink",
    defaultServing: "16 oz",
    defaultServingGrams: 473,
    carbsGrams: 50,
    proteinGrams: 4,
    fatGrams: 1,
    fiberGrams: 3,
    calories: 220,
    glycemicEstimate: "high",
  },
  {
    id: "drink-beer",
    name: "Beer (regular)",
    emoji: "\uD83C\uDF7A",
    category: "drink",
    defaultServing: "12 oz",
    defaultServingGrams: 355,
    carbsGrams: 13,
    proteinGrams: 2,
    fatGrams: 0,
    fiberGrams: 0,
    calories: 153,
    glycemicEstimate: "medium",
  },
  {
    id: "drink-sports-drink",
    name: "Sports Drink (Gatorade)",
    emoji: "\uD83E\uDD64",
    category: "drink",
    defaultServing: "20 oz bottle",
    defaultServingGrams: 591,
    carbsGrams: 34,
    proteinGrams: 0,
    fatGrams: 0,
    fiberGrams: 0,
    calories: 140,
    glycemicEstimate: "high",
  },
  {
    id: "drink-protein-shake",
    name: "Protein Shake",
    emoji: "\uD83E\uDD64",
    category: "drink",
    defaultServing: "1 scoop + water",
    defaultServingGrams: 350,
    carbsGrams: 5,
    proteinGrams: 25,
    fatGrams: 2,
    fiberGrams: 1,
    calories: 130,
    glycemicEstimate: "low",
  },
  {
    id: "drink-almond-milk",
    name: "Almond Milk (unsweetened)",
    emoji: "\uD83E\uDD5B",
    category: "drink",
    defaultServing: "1 cup",
    defaultServingGrams: 240,
    carbsGrams: 1,
    proteinGrams: 1,
    fatGrams: 2.5,
    fiberGrams: 0.5,
    calories: 30,
    glycemicEstimate: "low",
  },
  {
    id: "drink-apple-juice",
    name: "Apple Juice",
    emoji: "\uD83E\uDDC3",
    category: "drink",
    defaultServing: "1 cup",
    defaultServingGrams: 248,
    carbsGrams: 28,
    proteinGrams: 0.3,
    fatGrams: 0.3,
    fiberGrams: 0.5,
    calories: 114,
    glycemicEstimate: "high",
  },

  // ---- MIXED / FAST FOOD (15 items) ----
  {
    id: "mixed-pizza-cheese",
    name: "Pizza (cheese, 1 slice)",
    emoji: "\uD83C\uDF55",
    category: "mixed",
    defaultServing: "1 large slice",
    defaultServingGrams: 107,
    carbsGrams: 36,
    proteinGrams: 12,
    fatGrams: 10,
    fiberGrams: 2,
    calories: 285,
    glycemicEstimate: "high",
  },
  {
    id: "mixed-big-mac",
    name: "Big Mac",
    emoji: "\uD83C\uDF54",
    category: "mixed",
    defaultServing: "1 sandwich",
    defaultServingGrams: 200,
    carbsGrams: 45,
    proteinGrams: 25,
    fatGrams: 30,
    fiberGrams: 3,
    calories: 550,
    glycemicEstimate: "high",
  },
  {
    id: "mixed-burrito-bowl",
    name: "Burrito Bowl (Chipotle-style)",
    emoji: "\uD83C\uDF5B",
    category: "mixed",
    defaultServing: "1 bowl",
    defaultServingGrams: 510,
    carbsGrams: 55,
    proteinGrams: 40,
    fatGrams: 20,
    fiberGrams: 12,
    calories: 665,
    glycemicEstimate: "medium",
  },
  {
    id: "mixed-burrito",
    name: "Burrito (bean & cheese)",
    emoji: "\uD83C\uDF2F",
    category: "mixed",
    defaultServing: "1 large",
    defaultServingGrams: 300,
    carbsGrams: 60,
    proteinGrams: 22,
    fatGrams: 18,
    fiberGrams: 8,
    calories: 490,
    glycemicEstimate: "medium",
  },
  {
    id: "mixed-cheeseburger",
    name: "Cheeseburger",
    emoji: "\uD83C\uDF54",
    category: "mixed",
    defaultServing: "1 regular",
    defaultServingGrams: 156,
    carbsGrams: 33,
    proteinGrams: 17,
    fatGrams: 15,
    fiberGrams: 1.5,
    calories: 340,
    glycemicEstimate: "high",
  },
  {
    id: "mixed-chicken-nuggets",
    name: "Chicken Nuggets",
    emoji: "\uD83C\uDF57",
    category: "mixed",
    defaultServing: "10 pieces",
    defaultServingGrams: 160,
    carbsGrams: 30,
    proteinGrams: 23,
    fatGrams: 18,
    fiberGrams: 1,
    calories: 380,
    glycemicEstimate: "medium",
  },
  {
    id: "mixed-french-fries",
    name: "French Fries",
    emoji: "\uD83C\uDF5F",
    category: "mixed",
    defaultServing: "medium order",
    defaultServingGrams: 117,
    carbsGrams: 44,
    proteinGrams: 4,
    fatGrams: 16,
    fiberGrams: 4,
    calories: 340,
    glycemicEstimate: "high",
  },
  {
    id: "mixed-mac-and-cheese",
    name: "Mac and Cheese",
    emoji: "\uD83E\uDDC0",
    category: "mixed",
    defaultServing: "1 cup",
    defaultServingGrams: 200,
    carbsGrams: 47,
    proteinGrams: 11,
    fatGrams: 17,
    fiberGrams: 1.5,
    calories: 380,
    glycemicEstimate: "high",
  },
  {
    id: "mixed-fried-rice",
    name: "Fried Rice",
    emoji: "\uD83C\uDF5A",
    category: "mixed",
    defaultServing: "1 cup",
    defaultServingGrams: 200,
    carbsGrams: 47,
    proteinGrams: 9,
    fatGrams: 14,
    fiberGrams: 1,
    calories: 343,
    glycemicEstimate: "high",
  },
  {
    id: "mixed-sushi-roll",
    name: "Sushi Roll (California)",
    emoji: "\uD83C\uDF63",
    category: "mixed",
    defaultServing: "8 pieces",
    defaultServingGrams: 220,
    carbsGrams: 38,
    proteinGrams: 9,
    fatGrams: 7,
    fiberGrams: 2,
    calories: 255,
    glycemicEstimate: "high",
  },
  {
    id: "mixed-ramen",
    name: "Ramen (noodle soup)",
    emoji: "\uD83C\uDF5C",
    category: "mixed",
    defaultServing: "1 bowl",
    defaultServingGrams: 450,
    carbsGrams: 60,
    proteinGrams: 20,
    fatGrams: 15,
    fiberGrams: 3,
    calories: 450,
    glycemicEstimate: "high",
  },
  {
    id: "mixed-sandwich-turkey",
    name: "Turkey Sandwich",
    emoji: "\uD83E\uDD6A",
    category: "mixed",
    defaultServing: "1 sandwich",
    defaultServingGrams: 200,
    carbsGrams: 35,
    proteinGrams: 22,
    fatGrams: 8,
    fiberGrams: 3,
    calories: 300,
    glycemicEstimate: "medium",
  },
  {
    id: "mixed-grilled-cheese",
    name: "Grilled Cheese Sandwich",
    emoji: "\uD83E\uDD6A",
    category: "mixed",
    defaultServing: "1 sandwich",
    defaultServingGrams: 130,
    carbsGrams: 28,
    proteinGrams: 12,
    fatGrams: 18,
    fiberGrams: 1,
    calories: 330,
    glycemicEstimate: "high",
  },
  {
    id: "mixed-tacos",
    name: "Tacos (beef, 2)",
    emoji: "\uD83C\uDF2E",
    category: "mixed",
    defaultServing: "2 tacos",
    defaultServingGrams: 170,
    carbsGrams: 24,
    proteinGrams: 18,
    fatGrams: 16,
    fiberGrams: 3,
    calories: 310,
    glycemicEstimate: "medium",
  },
  {
    id: "mixed-pad-thai",
    name: "Pad Thai",
    emoji: "\uD83C\uDF5C",
    category: "mixed",
    defaultServing: "1 plate",
    defaultServingGrams: 350,
    carbsGrams: 55,
    proteinGrams: 20,
    fatGrams: 14,
    fiberGrams: 2,
    calories: 430,
    glycemicEstimate: "high",
  },
];

/**
 * Search the common foods list by name (case-insensitive).
 */
export function searchCommonFoods(query: string): CommonFoodItem[] {
  if (!query.trim()) return [];
  const lowerQuery = query.toLowerCase().trim();

  return COMMON_FOODS.filter((food) =>
    food.name.toLowerCase().includes(lowerQuery)
  );
}

/**
 * Get common foods by category.
 */
export function getCommonFoodsByCategory(
  category: CommonFoodItem["category"]
): CommonFoodItem[] {
  return COMMON_FOODS.filter((food) => food.category === category);
}

/**
 * Get a specific common food by ID.
 */
export function getCommonFoodById(id: string): CommonFoodItem | undefined {
  return COMMON_FOODS.find((food) => food.id === id);
}
